_format_version: "3.0"
_transform: true

services:
  - name: search-service
    url: http://search-api:8080
    routes:
      - name: search-route
        methods: [GET]
        paths:
          - /api/search
        strip_path: false
      - name: suggest-route
        methods: [GET]
        paths:
          - /api/search/suggest
        strip_path: false
    plugins:
      - name: jwt
        config:
          key_claim_name: iss
          claims_to_verify:
            - exp
          run_on_preflight: true

consumers:
  - username: keycloak-issuer
    jwt_secrets:
      # iss must match Keycloak token issuer (depends on host used to call /token).
      - key: "http://localhost:8081/realms/ecommerce"
        algorithm: RS256
        # RS256 public key (PEM) from Keycloak JWKS x5c for kid with use=sig. If realm keys rotate, refresh:
        # curl -s http://localhost:8081/realms/ecommerce/protocol/openid-connect/certs
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApnwJCqbBJLsQ5SNgGmPp
          Nu1qzZx+UkXmc6OhD1qYIimf0Jale+gDXNb5MLIWQDRdrspf8/KHinyOrVt/j/bp
          P2Cu2SG3aKR0h5JNBvvpimXzV7cfu5OjABu3p8JvBioupFOUKtIB4+yPLp4/8hPQ
          zjVsVOOlFEv/o896BOR6agbTClo34ARVDyznQNnoFM24sIuSSM7kWi7Pdseg2KNs
          a2ZtXR5PhDUho7aamGBn6gwTaWIFdLHLF+G83czWRHEdu/m6LQP8O+3GjwNPvzfr
          NvDwiknLqwuTpHwku0/HxxCecIZw2hRVW+3QAd4YbZPFWkey6PtpoCspaSBsonDS
          KQIDAQAB
          -----END PUBLIC KEY-----
        secret: "unused-for-rs256"
      # k6 en Docker (Windows/Mac) suele obtener tokens contra host.docker.internal.
      - key: "http://host.docker.internal:8081/realms/ecommerce"
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApnwJCqbBJLsQ5SNgGmPp
          Nu1qzZx+UkXmc6OhD1qYIimf0Jale+gDXNb5MLIWQDRdrspf8/KHinyOrVt/j/bp
          P2Cu2SG3aKR0h5JNBvvpimXzV7cfu5OjABu3p8JvBioupFOUKtIB4+yPLp4/8hPQ
          zjVsVOOlFEv/o896BOR6agbTClo34ARVDyznQNnoFM24sIuSSM7kWi7Pdseg2KNs
          a2ZtXR5PhDUho7aamGBn6gwTaWIFdLHLF+G83czWRHEdu/m6LQP8O+3GjwNPvzfr
          NvDwiknLqwuTpHwku0/HxxCecIZw2hRVW+3QAd4YbZPFWkey6PtpoCspaSBsonDS
          KQIDAQAB
          -----END PUBLIC KEY-----
        secret: "unused-for-rs256"
